id: P001781
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6912
  title: ཁྱེད་ཀྱིས་ཐཱན་ཉུང་འཚོ་བར་རྒྱུས་མངའ་ཡོད་དམ།
  author: ''
  volumes:
    d2ee999bf8344f079f4b8283dc2219fc:
      image_group_id: I3CN6914
      title: ''
      volume_number: 1
      total_pages: 216
